<a href="https://colab.research.google.com/github/heyanugrah/Transformers/blob/main/codeTransformerMe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import random

In [2]:
from torch import nn

In [3]:
word = "anugrah is learning"

In [4]:
vocab = ["<pad>","anugrah","is","learning","[SEP]","<unk>","<CLS>"];

In [5]:

vocab_dict={}

#creating vocabulory
for index,vocab_item in enumerate(vocab):
  vocab_dict[index] = vocab_item

In [6]:
""
print(vocab_dict)

{0: '<pad>', 1: 'anugrah', 2: 'is', 3: 'learning', 4: '[SEP]', 5: '<unk>', 6: '<CLS>'}


In [7]:
input_text = "anugrah is learning okay.oo"

In [8]:
#Tokenize and Add CLS,PAD and SEP token with input

tokenList = []

tokenList.append("[CLS]")

for word in input_text.split():

    # Check for sentence ending with '.'
    if word.endswith("."):

        clean_word = word[:-1]

        if clean_word in vocab:
            tokenList.append(clean_word)
        else:
            tokenList.append("<unk>")

        tokenList.append("[SEP]")

    else:

        if word in vocab:
            tokenList.append(word)
        else:
            tokenList.append("<unk>")

# Add final separator if not already present
if tokenList[-1] != "[SEP]":
    tokenList.append("[SEP]")

print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [9]:
print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [10]:
#convert the tokenList to tokenId

In [11]:
tokenIDList = []
print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [12]:
vectorList = []

#converting wordList to vectorList
for word in tokenList:
    for key, value in vocab_dict.items():
        if value == word:
            #print(word, "->", key)
            vectorList.append(key)
            tokenIDList.append(value)

In [13]:
print(vectorList)
print(tokenIDList)

[1, 2, 3, 5, 4]
['anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [14]:
max_seq_length = 10 #total of 10 words in a sentence

# Adding padding zero to make sequence length equal
while len(vectorList) < max_seq_length:
    vectorList.append(0)

vectorList


[1, 2, 3, 5, 4, 0, 0, 0, 0, 0]

In [15]:
#creating attention mask
attentionMaskList = []

attentionMaskList = [1 if token != 0 else 0 for token in vectorList]
print(attentionMaskList)

[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]


In [16]:
#token embbedings

In [17]:
import torch.nn as nn

In [18]:
#convert list to tensors

In [19]:
trs = torch.tensor(vectorList)
type(trs)

torch.Tensor

In [20]:
print(trs)

tensor([1, 2, 3, 5, 4, 0, 0, 0, 0, 0])


In [21]:
dim = 10
embbedings = nn.Embedding(
    num_embeddings=dim,
    embedding_dim=dim
)

In [22]:
embedings = embbedings(trs)

In [23]:
embedings

tensor([[ 3.0250,  0.9517,  1.7619,  0.2854,  2.1508, -1.7152,  1.1351, -1.2997,
          0.2757, -0.8842],
        [ 1.9170,  0.2557, -0.5498, -0.3816,  1.0304,  1.2729,  0.2246,  0.2788,
          2.0329,  1.0519],
        [ 0.3435,  0.8310, -0.6517,  2.3462,  1.2783, -0.7354,  0.2372,  0.7514,
         -0.1708,  0.9290],
        [ 1.1169, -0.8867, -0.3443, -0.9323, -0.8550, -1.0352, -0.6674,  0.0770,
          0.0984,  0.5315],
        [-2.4284, -0.0262, -0.2563, -0.2904,  0.3763,  0.2955,  0.1730, -0.3946,
          0.2968,  0.2253],
        [ 1.4213, -0.1267, -0.0886,  0.3791, -1.6038, -1.1553, -0.2043, -0.4619,
         -0.2528, -1.4112],
        [ 1.4213, -0.1267, -0.0886,  0.3791, -1.6038, -1.1553, -0.2043, -0.4619,
         -0.2528, -1.4112],
        [ 1.4213, -0.1267, -0.0886,  0.3791, -1.6038, -1.1553, -0.2043, -0.4619,
         -0.2528, -1.4112],
        [ 1.4213, -0.1267, -0.0886,  0.3791, -1.6038, -1.1553, -0.2043, -0.4619,
         -0.2528, -1.4112],
        [ 1.4213, -

In [24]:
embedings.shape #10 tokens , #10 dimensional

torch.Size([10, 10])

In [25]:
#positional encoding

In [26]:

'''
Formula:

PE(pos, 2i)   = sin(pos / 10000^(2i/d_model))
    PE(pos, 2i+1) = cos(pos / 10000^(2i/d_model))
'''
import math

pev = torch.zeros(max_seq_length, dim) #position encoding vector
pev

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
pev.shape

torch.Size([10, 10])

In [28]:
#position
position = torch.arange(0,10)
position

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
position.shape

torch.Size([10])

In [30]:
#add the shape to make matrix addition
position = position.unsqueeze(1)

In [31]:
position

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [32]:
position.shape

torch.Size([10, 1])

In [33]:
print(pev)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [34]:
div_term = torch.exp(
    torch.arange(0, dim, 2)
    * (-math.log(10000.0) / dim)
)

#controlling oscillation speed of sin and cos waves
print(div_term)

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])


In [35]:
pev[:, 0::2] = torch.sin(position * div_term) #even apply, start from 0 to end , every second number
pev[:, 1::2] = torch.cos(position * div_term) #odd apply, start from 0 to end , every second number

In [36]:
print(pev)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
          9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
          9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
          9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
          9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00],
        [-9.5892e-01,  2.8366e-01,  7.1207e-01,  7.0211e-01,  1.2526e-01,
          9.9212e-01,  1.9904e-02,  9.9980e-01,  3.1548e-03,  1.0000e+00],
        [-2.7942e-01,  9.6017e-01,  8.1396e-01,  5.8092e-01,  1.5014e-01,
          9.8866e-01,  2.3884e-0

In [37]:
combined_embedings = pev + embedings #CE = PE + Embbedings

In [38]:
print(combined_embedings)

tensor([[ 3.0250,  1.9517,  1.7619,  1.2854,  2.1508, -0.7152,  1.1351, -0.2997,
          0.2757,  0.1158],
        [ 2.7585,  0.7960, -0.3919,  0.6058,  1.0555,  2.2726,  0.2286,  1.2788,
          2.0336,  2.0519],
        [ 1.2528,  0.4149, -0.3400,  3.2964,  1.3285,  0.2633,  0.2452,  1.7513,
         -0.1696,  1.9290],
        [ 1.2580, -1.8767,  0.1134, -0.0432, -0.7797, -0.0381, -0.6554,  1.0769,
          0.1003,  1.5315],
        [-3.1852, -0.6799,  0.3360,  0.5153,  0.4766,  1.2905,  0.1889,  0.6052,
          0.2994,  1.2253],
        [ 0.4624,  0.1570,  0.6234,  1.0812, -1.4785, -0.1632, -0.1844,  0.5379,
         -0.2496, -0.4112],
        [ 1.1419,  0.8335,  0.7253,  0.9600, -1.4537, -0.1666, -0.1804,  0.5378,
         -0.2490, -0.4112],
        [ 2.0783,  0.6273,  0.8068,  0.8242, -1.4289, -0.1707, -0.1764,  0.5377,
         -0.2484, -0.4112],
        [ 2.4107, -0.2722,  0.8658,  0.6773, -1.4042, -0.1754, -0.1724,  0.5376,
         -0.2477, -0.4112],
        [ 1.8335, -

In [39]:
print(combined_embedings.shape)

torch.Size([10, 10])


In [40]:
dim

10

In [41]:
#Encoder
import torch.nn.functional as F

class Encoder(nn.Module):

  def __init__(self):
      super().__init__()
      self.dim = dim
      self.Wq = nn.Linear(dim,dim) #weightedQuery
      self.Wk = nn.Linear(dim,dim) #weightKey
      self.Wv = nn.Linear(dim,dim) #weightedValue

      #normalization 1
      self.norm1 = nn.LayerNorm(dim)

      #feed forward nueral network
      self.ffn = nn.Sequential(
           nn.Linear(dim,dim * 4),
           nn.ReLU(),
           nn.Linear(dim * 4,dim)
      )

      #normalization 2
      self.norm2 = nn.LayerNorm(dim)

  def selfAttention(self, x):
        # K and Q are already the results of the linear projection
        K = self.Wk(x)
        Q = self.Wq(x)
        V = self.Wv(x)

        # Use @ for matrix multiplication and .transpose() for the Key
        scores = Q @ K.transpose(-2, -1)

        print('key shape : ',K.shape)
        return scores,K,V

  def forward(self,combined_embedings,attention_mask):

    #calculating self attention
    scores,K,V = self.selfAttention(combined_embedings)

    #scaled self attention
    scaled_score = scores / math.sqrt(self.dim) #dimension of key

    scaled_score = scaled_score.masked_fill(
        attention_mask == 0,
        -1e9
    )

    #applying softmax to scaled_score
    attention_weights = F.softmax(
        scaled_score,
        dim=-1) #-1 for each row apply softmax to all columns

    print('softmax applied :' , attention_weights)
    #creating context vecto
    context_vector = attention_weights @ V

    #adding residual connection 1 (context_vector + combined_embedings)
    residual_vector_1 = context_vector + combined_embedings

    #normalization of residual vector
    normalized_vector_1 = self.norm1(residual_vector_1)

    print('context scores: ',scores.shape)
    print('scores: ',scores.shape)
    print('scaled scores: ',scores.shape)

    #Feeding to Feed Forward Nueral Network
    ffn_output = self.ffn(normalized_vector_1)
    print('ffn_output: ',ffn_output)

    #residual connection 2 (normalized_vector + ffn_output)
    residual_vector_2 = normalized_vector_1 + ffn_output

    #normalization 2
    normalized_vector_2 = self.norm2(residual_vector_2)

    return normalized_vector_2,K,V


$$\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V$$

In [42]:
encoderLayer = Encoder()

#convert attentionList to tensor
attention_mask = torch.tensor(
    attentionMaskList
)

encoder_output,K,V = encoderLayer(combined_embedings,attention_mask)

print("encoder_output :" ,encoder_output)
print("key vector to decoder ", K)
print("Value vector to decoder ", V)
print("Attention mask" ,attention_mask)


key shape :  torch.Size([10, 10])
softmax applied : tensor([[0.4089, 0.0403, 0.1545, 0.1051, 0.2911, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.6409, 0.0310, 0.1252, 0.0822, 0.1207, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3862, 0.0740, 0.2064, 0.1134, 0.2200, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1581, 0.2303, 0.2282, 0.1975, 0.1859, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1971, 0.3078, 0.1717, 0.1860, 0.1374, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0952, 0.1987, 0.2015, 0.1885, 0.3161, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1210, 0.1605, 0.1979, 0.1796, 0.3409, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1283, 0.1381, 0.2017, 0.1779, 0.3540, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1085, 0.1492, 0.2099, 0.1886, 0.3439, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0843, 0.1889, 0.2098, 0.2022, 0.3149, 0.0000, 

In [43]:
# Accessing the weight matrix
print("Wq weight shape:", encoderLayer.Wq.weight.shape)
print("Wq weight:\n", encoderLayer.Wq.weight)

# Accessing the bias vector
print("Wq bias shape:", encoderLayer.Wq.bias.shape)
print("Wq bias:\n", encoderLayer.Wq.bias)

Wq weight shape: torch.Size([10, 10])
Wq weight:
 Parameter containing:
tensor([[-0.2433,  0.0467, -0.1391,  0.0518, -0.3120, -0.1983,  0.1010,  0.0900,
         -0.0838,  0.0608],
        [-0.2307,  0.1211, -0.3016,  0.0670,  0.0959,  0.2335,  0.0656,  0.0053,
          0.1147, -0.0268],
        [ 0.2102,  0.1173, -0.0882,  0.2868,  0.2718, -0.1973,  0.1144, -0.2601,
          0.1961,  0.1849],
        [ 0.2881, -0.1227, -0.0645,  0.0501,  0.1754, -0.0823, -0.2121, -0.1931,
         -0.0528,  0.2000],
        [ 0.3047, -0.0968, -0.0558,  0.0721, -0.2225, -0.2109,  0.3152,  0.2250,
          0.0886, -0.1885],
        [ 0.1559,  0.0140, -0.0089,  0.0497, -0.2496, -0.0434,  0.1880,  0.0004,
         -0.0455,  0.1357],
        [ 0.0603,  0.1554,  0.1923, -0.2979,  0.0978, -0.2095,  0.1861, -0.0702,
         -0.2385,  0.1932],
        [ 0.2586,  0.2812, -0.0259,  0.0900, -0.2379,  0.1725,  0.1238,  0.2196,
          0.0893,  0.0483],
        [ 0.0227,  0.0094, -0.2651,  0.0643,  0.1070,  0

Multihead - Encoder


In [44]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math


class MultiHeadEncoder(nn.Module):

    def __init__(self, dim, no_of_heads,dropout):
        super().__init__()

        # ✅ CORRECT: Embedding dimension must be divisible by number of heads
        assert dim % no_of_heads == 0

        self.dim = dim
        self.no_of_heads = no_of_heads
        self.head_vector_dim = dim // no_of_heads

        print("head_vector_dim:", self.head_vector_dim)

        # Query, Key, Value projections
        self.Wq = nn.Linear(dim, dim)
        self.Wk = nn.Linear(dim, dim)
        self.Wv = nn.Linear(dim, dim)

        # Output projection
        self.Wo = nn.Linear(dim, dim)

        # Layer Normalization 1
        self.norm1 = nn.LayerNorm(dim)

        # Feed Forward Network
        self.ffn = nn.Sequential(
            nn.Linear(dim, dim * 4),
            nn.ReLU(),
            nn.Linear(dim * 4, dim)
        )

        # Layer Normalization 2
        self.norm2 = nn.LayerNorm(dim)

        #dropout
        self.dropout = nn.Dropout(dropout)

    def selfAttentionMultiHead(self, x):

        batch_size, seq_len, _ = x.shape

        print('x shape in self-attention function', x.shape)

        K = self.Wk(x)
        Q = self.Wq(x)
        V = self.Wv(x)

        print("K shape before :", K.shape)
        print("Q shape before :", Q.shape)
        print("V shape before :", V.shape)

        # ✅ CORRECT: Split embedding dimension into heads
        K = K.view(
            batch_size,
            seq_len,
            self.no_of_heads,
            self.head_vector_dim
        )

        Q = Q.view(
            batch_size,
            seq_len,
            self.no_of_heads,
            self.head_vector_dim
        )

        V = V.view(
            batch_size,
            seq_len,
            self.no_of_heads,
            self.head_vector_dim
        )

        # ✅ CORRECT: Move head dimension to front
        K = K.transpose(1, 2) #e([10, 10]) --> [2,10,5]
        Q = Q.transpose(1, 2)
        V = V.transpose(1, 2)

        print("K shape After :", K.shape)
        print("Q shape After :", Q.shape)
        print("V shape After :", V.shape)

        # ✅ CORRECT: Attention score calculation
        scores = Q @ K.transpose(-2, -1)

        return scores, K, V

    def forward(self, combined_embeddings, attention_mask):

        # Multi-head attention
        scores, K, V = self.selfAttentionMultiHead(
            combined_embeddings
        )

        # ✅ CORRECT: Scale by sqrt(head_dim)
        scaled_scores = scores / math.sqrt(
            self.head_vector_dim
        )

        # Apply mask
        scaled_scores = scaled_scores.masked_fill(
            attention_mask == 0,
            -1e9
        )

        print("scaled score:",
              scaled_scores)

        # Softmax
        attention_weights = F.softmax(
            scaled_scores,
            dim=-1 #-1 for each row apply softmax to all columns
        )
        print("attention_weights shape:",
              attention_weights.shape)


        #Applying droupout on attention-weights
        dropout_output_1 = self.dropout(
            attention_weights
            )

        print("droupout shape:",
              dropout_output_1.shape)


        # ✅ CORRECT: Context Vector
        context_vector = dropout_output_1 @ V

        print("context_vector shape before concat:",
              context_vector.shape)

        # ✅ CORRECT: Concatenate heads
        context_vector = context_vector.transpose(
            0,
            1
        )

        context_vector = context_vector.contiguous().view(
            batch_size,
            combined_embeddings.shape[1],
            self.dim
        )

        print("context_vector shape after concat:",
              context_vector.shape)

        # Output projection
        Wo = self.Wo(context_vector)

        print("Output Projection (Wo) shape :",
              Wo.shape)

        # ✅ CORRECT: Residual Connection 1
        residual_vector_1 = Wo + combined_embeddings

        # ✅ CORRECT: LayerNorm 1
        normalized_vector_1 = self.norm1(
            residual_vector_1
        )

        # Feed Forward Network
        ffn_output = self.ffn(
            normalized_vector_1
        )

        #dropout after FFN
        dropout_output_2 = self.dropout(
            ffn_output
        )

        print("droupout2 shape:",
              dropout_output_2.shape)

        # ✅ CORRECT: Residual Connection 2
        residual_vector_2 = (
            normalized_vector_1 +
            dropout_output_2
        )

        # ✅ CORRECT: LayerNorm 2
        normalized_vector_2 = self.norm2(
            residual_vector_2
        )


        return normalized_vector_2, K, V

In [45]:

# --------------------------
# Example Usage
# --------------------------

# seq_len = 10
# embedding_dim = 10
# num_heads = 2
# batch_size = 1

# encoder = MultiHeadEncoder(
#     embedding_dim,
#     num_heads,
#     dropout=0.1
# )


# # Attention mask
# attention_mask = torch.tensor(
#     attentionMaskList
# )

# print("Attention mask" ,attention_mask)

# print("combined_embedings before : ",combined_embedings)
# combined_embedings = combined_embedings.unsqueeze(0);
# print("combined_embedings After : ",combined_embedings)

# output, K, V = encoder(
#     combined_embedings,
#     attention_mask
# )

# print("\nFinal Output Shape:", output.shape)

In [46]:
class TransformerEncoderStack(nn.Module):

  def __init__(self,embedding_dim,num_heads,dropout,layers):
    super().__init__()

    self.encoderLayers = nn.ModuleList([
               MultiHeadEncoder(
                    embedding_dim,
                    num_heads,
                    dropout
                )
           for _ in range(layers)
    ])

  def forward(self,combined_embedings,attention_mask):
    running_var = combined_embedings

    for encoder in self.encoderLayers:
      output, K, V = encoder(
      running_var,
      attention_mask
      )
      running_var = output

    return running_var, K, V


In [47]:
seq_len = 10
embedding_dim = 10
num_heads = 2
batch_size = 1

print(attention_mask.shape)

te = TransformerEncoderStack(embedding_dim=10,num_heads=2, dropout=0.1, layers=5)

combined_embedings=combined_embedings.unsqueeze(0)

model = te(combined_embedings=combined_embedings,attention_mask=attention_mask)

torch.Size([10])
head_vector_dim: 5
head_vector_dim: 5
head_vector_dim: 5
head_vector_dim: 5
head_vector_dim: 5
x shape in self-attention function torch.Size([1, 10, 10])
K shape before : torch.Size([1, 10, 10])
Q shape before : torch.Size([1, 10, 10])
V shape before : torch.Size([1, 10, 10])
K shape After : torch.Size([1, 2, 10, 5])
Q shape After : torch.Size([1, 2, 10, 5])
V shape After : torch.Size([1, 2, 10, 5])
scaled score: tensor([[[[-2.4008e-01,  1.1137e+00,  1.5442e-01,  8.5344e-02,  2.9580e-01,
           -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
          [-2.0737e-01,  9.4003e-01, -5.7273e-02, -1.4147e-01,  3.6592e-01,
           -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
          [-1.5855e-01,  8.2796e-01,  2.2435e-02, -2.1978e-02,  1.9685e-01,
           -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
          [ 1.9433e-01,  1.0020e-01, -3.0170e-01, -3.2929e-01,  5.6461e-02,
           -1.0000e+09, -1.0000

In [48]:

# --------------------------
# Example Usage
# --------------------------

# seq_len = 10
# embedding_dim = 10
# num_heads = 2
# batch_size = 1

# encoder = MultiHeadEncoder(
#     embedding_dim,
#     num_heads,
#     dropout=0.1
# )


# # Attention mask
# attention_mask = torch.tensor(
#     attentionMaskList
# )

# print("Attention mask" ,attention_mask)

# print("combined_embedings before : ",combined_embedings)
# combined_embedings = combined_embedings.unsqueeze(0);
# print("combined_embedings After : ",combined_embedings)

# output, K, V = encoder(
#     combined_embedings,
#     attention_mask
# )

# print("\nFinal Output Shape:", output.shape)