<a href="https://colab.research.google.com/github/heyanugrah/Transformers/blob/main/codeTransformerMe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import random

In [2]:
from torch import nn

In [3]:
word = "anugrah is learning"

In [4]:
vocab = ["<pad>","anugrah","is","learning","[SEP]","<unk>","<CLS>"];

In [5]:

vocab_dict={}

#creating vocabulory
for index,vocab_item in enumerate(vocab):
  vocab_dict[index] = vocab_item

In [6]:
""
print(vocab_dict)

{0: '<pad>', 1: 'anugrah', 2: 'is', 3: 'learning', 4: '[SEP]', 5: '<unk>', 6: '<CLS>'}


In [7]:
input_text = "anugrah is learning okay.oo"

In [8]:
#Tokenize and Add CLS,PAD and SEP token with input

tokenList = []

tokenList.append("[CLS]")

for word in input_text.split():

    # Check for sentence ending with '.'
    if word.endswith("."):

        clean_word = word[:-1]

        if clean_word in vocab:
            tokenList.append(clean_word)
        else:
            tokenList.append("<unk>")

        tokenList.append("[SEP]")

    else:

        if word in vocab:
            tokenList.append(word)
        else:
            tokenList.append("<unk>")

# Add final separator if not already present
if tokenList[-1] != "[SEP]":
    tokenList.append("[SEP]")

print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [9]:
print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [10]:
#convert the tokenList to tokenId

In [11]:
tokenIDList = []
print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [12]:
vectorList = []

#converting wordList to vectorList
for word in tokenList:
    for key, value in vocab_dict.items():
        if value == word:
            #print(word, "->", key)
            vectorList.append(key)
            tokenIDList.append(value)

In [13]:
print(vectorList)
print(tokenIDList)

[1, 2, 3, 5, 4]
['anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [14]:
max_seq_length = 10 #total of 10 words in a sentence

# Adding padding zero to make sequence length equal
while len(vectorList) < max_seq_length:
    vectorList.append(0)

vectorList


[1, 2, 3, 5, 4, 0, 0, 0, 0, 0]

In [15]:
#creating attention mask
attentionMaskList = []

attentionMaskList = [1 if token != 0 else 0 for token in vectorList]
print(attentionMaskList)

[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]


In [16]:
#token embbedings

In [17]:
import torch.nn as nn

In [18]:
#convert list to tensors

In [19]:
trs = torch.tensor(vectorList)
type(trs)

torch.Tensor

In [20]:
print(trs)

tensor([1, 2, 3, 5, 4, 0, 0, 0, 0, 0])


In [21]:
dim = 10
embbedings = nn.Embedding(
    num_embeddings=dim,
    embedding_dim=dim
)

In [22]:
embedings = embbedings(trs)

In [23]:
embedings

tensor([[-0.0376, -0.1956,  0.4848, -1.2354,  0.6487, -0.7643, -0.0110,  1.3396,
         -0.1334, -0.6700],
        [ 0.0505,  0.0118, -0.3219,  0.9326, -0.1808, -0.5516,  0.5498,  0.3967,
          1.8117, -0.4213],
        [-0.5303,  0.9980, -0.8769,  0.5488,  0.3429, -1.3574,  0.9436, -0.9214,
         -1.1682, -0.2706],
        [ 0.3775,  0.0673, -1.2496,  0.6422, -1.4991,  1.3974, -0.4521,  1.6004,
          0.1411,  1.6715],
        [-0.7391, -0.9606,  0.9537,  2.1514,  0.7622, -0.7239,  1.2199,  0.6392,
         -1.4645,  1.0563],
        [-1.1568, -1.3713,  1.0565,  0.2976,  0.4924, -0.1717, -1.8293,  0.1657,
          1.5208,  1.0344],
        [-1.1568, -1.3713,  1.0565,  0.2976,  0.4924, -0.1717, -1.8293,  0.1657,
          1.5208,  1.0344],
        [-1.1568, -1.3713,  1.0565,  0.2976,  0.4924, -0.1717, -1.8293,  0.1657,
          1.5208,  1.0344],
        [-1.1568, -1.3713,  1.0565,  0.2976,  0.4924, -0.1717, -1.8293,  0.1657,
          1.5208,  1.0344],
        [-1.1568, -

In [24]:
embedings.shape #10 tokens , #10 dimensional

torch.Size([10, 10])

In [25]:
#positional encoding

In [26]:

'''
Formula:

PE(pos, 2i)   = sin(pos / 10000^(2i/d_model))
    PE(pos, 2i+1) = cos(pos / 10000^(2i/d_model))
'''
import math

pev = torch.zeros(max_seq_length, dim) #position encoding vector
pev

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
pev.shape

torch.Size([10, 10])

In [28]:
#position
position = torch.arange(0,10)
position

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
position.shape

torch.Size([10])

In [30]:
#add the shape to make matrix addition
position = position.unsqueeze(1)

In [31]:
position

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [32]:
position.shape

torch.Size([10, 1])

In [33]:
print(pev)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [34]:
div_term = torch.exp(
    torch.arange(0, dim, 2)
    * (-math.log(10000.0) / dim)
)

#controlling oscillation speed of sin and cos waves
print(div_term)

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])


In [35]:
pev[:, 0::2] = torch.sin(position * div_term) #even apply, start from 0 to end , every second number
pev[:, 1::2] = torch.cos(position * div_term) #odd apply, start from 0 to end , every second number

In [36]:
print(pev)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
          9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
          9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
          9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
          9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00],
        [-9.5892e-01,  2.8366e-01,  7.1207e-01,  7.0211e-01,  1.2526e-01,
          9.9212e-01,  1.9904e-02,  9.9980e-01,  3.1548e-03,  1.0000e+00],
        [-2.7942e-01,  9.6017e-01,  8.1396e-01,  5.8092e-01,  1.5014e-01,
          9.8866e-01,  2.3884e-0

In [37]:
combined_embedings = pev + embedings #CE = PE + Embbedings

In [38]:
print(combined_embedings)

tensor([[-0.0376,  0.8044,  0.4848, -0.2354,  0.6487,  0.2357, -0.0110,  2.3396,
         -0.1334,  0.3300],
        [ 0.8919,  0.5521, -0.1641,  1.9201, -0.1556,  0.4481,  0.5537,  1.3967,
          1.8123,  0.5787],
        [ 0.3790,  0.5819, -0.5652,  1.4990,  0.3932, -0.3587,  0.9516,  0.0786,
         -1.1669,  0.7294],
        [ 0.5186, -0.9227, -0.7918,  1.5313, -1.4238,  2.3946, -0.4401,  2.6004,
          0.1429,  2.6715],
        [-1.4959, -1.6143,  1.5460,  2.9571,  0.8625,  0.2711,  1.2358,  1.6391,
         -1.4620,  2.0563],
        [-2.1158, -1.0877,  1.7686,  0.9997,  0.6176,  0.8205, -1.8094,  1.1655,
          1.5239,  2.0344],
        [-1.4363, -0.4112,  1.8705,  0.8785,  0.6425,  0.8170, -1.8054,  1.1654,
          1.5246,  2.0343],
        [-0.4999, -0.6174,  1.9520,  0.7428,  0.6673,  0.8129, -1.8014,  1.1653,
          1.5252,  2.0343],
        [-0.1675, -1.5168,  2.0110,  0.5959,  0.6920,  0.8082, -1.7974,  1.1652,
          1.5258,  2.0343],
        [-0.7447, -

In [39]:
print(combined_embedings.shape)

torch.Size([10, 10])


In [40]:
dim

10

In [41]:
#Encoder
import torch.nn.functional as F

class Encoder(nn.Module):

  def __init__(self):
      super().__init__()
      self.dim = dim
      self.Wq = nn.Linear(dim,dim) #weightedQuery
      self.Wk = nn.Linear(dim,dim) #weightKey
      self.Wv = nn.Linear(dim,dim) #weightedValue

      #normalization 1
      self.norm1 = nn.LayerNorm(dim)

      #feed forward nueral network
      self.ffn = nn.Sequential(
           nn.Linear(dim,dim * 4),
           nn.ReLU(),
           nn.Linear(dim * 4,dim)
      )

      #normalization 2
      self.norm2 = nn.LayerNorm(dim)

  def selfAttention(self, x):
        # K and Q are already the results of the linear projection
        K = self.Wk(x)
        Q = self.Wq(x)
        V = self.Wv(x)

        # Use @ for matrix multiplication and .transpose() for the Key
        scores = Q @ K.transpose(-2, -1)

        print('key shape : ',K.shape)
        return scores,K,V

  def forward(self,combined_embedings,attention_mask):

    #calculating self attention
    scores,K,V = self.selfAttention(combined_embedings)

    #scaled self attention
    scaled_score = scores / math.sqrt(self.dim) #dimension of key

    scaled_score = scaled_score.masked_fill(
        attention_mask == 0,
        -1e9
    )

    #applying softmax to scaled_score
    attention_weights = F.softmax(
        scaled_score,
        dim=-1) #-1 for each row apply softmax to all columns

    print('softmax applied :' , attention_weights)
    #creating context vecto
    context_vector = attention_weights @ V

    #adding residual connection 1 (context_vector + combined_embedings)
    residual_vector_1 = context_vector + combined_embedings

    #normalization of residual vector
    normalized_vector_1 = self.norm1(residual_vector_1)

    print('context scores: ',scores.shape)
    print('scores: ',scores.shape)
    print('scaled scores: ',scores.shape)

    #Feeding to Feed Forward Nueral Network
    ffn_output = self.ffn(normalized_vector_1)
    print('ffn_output: ',ffn_output)

    #residual connection 2 (normalized_vector + ffn_output)
    residual_vector_2 = normalized_vector_1 + ffn_output

    #normalization 2
    normalized_vector_2 = self.norm2(residual_vector_2)

    return normalized_vector_2,K,V


$$\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V$$

In [42]:
encoderLayer = Encoder()

#convert attentionList to tensor
attention_mask = torch.tensor(
    attentionMaskList
)

encoder_output,K,V = encoderLayer(combined_embedings,attention_mask)

print("encoder_output :" ,encoder_output)
print("key vector to decoder ", K)
print("Value vector to decoder ", V)
print("Attention mask" ,attention_mask)


key shape :  torch.Size([10, 10])
softmax applied : tensor([[0.1643, 0.1448, 0.1887, 0.2553, 0.2469, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.2284, 0.1926, 0.1579, 0.1574, 0.2638, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.2079, 0.1748, 0.1862, 0.1377, 0.2934, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.2907, 0.1891, 0.1994, 0.1383, 0.1826, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.4117, 0.2873, 0.1405, 0.0582, 0.1023, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3666, 0.3249, 0.1346, 0.0916, 0.0822, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3286, 0.2996, 0.1483, 0.1152, 0.1083, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3066, 0.2889, 0.1640, 0.1150, 0.1256, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3189, 0.3041, 0.1691, 0.0943, 0.1136, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3492, 0.3283, 0.1577, 0.0772, 0.0877, 0.0000, 

In [43]:
# Accessing the weight matrix
print("Wq weight shape:", encoderLayer.Wq.weight.shape)
print("Wq weight:\n", encoderLayer.Wq.weight)

# Accessing the bias vector
print("Wq bias shape:", encoderLayer.Wq.bias.shape)
print("Wq bias:\n", encoderLayer.Wq.bias)

Wq weight shape: torch.Size([10, 10])
Wq weight:
 Parameter containing:
tensor([[-0.0700, -0.1514,  0.0111,  0.1874,  0.1338, -0.2918, -0.1163, -0.1571,
         -0.0540,  0.3044],
        [ 0.1406, -0.2578, -0.2075,  0.0719, -0.2956,  0.1957, -0.2478,  0.2963,
          0.3054,  0.1566],
        [ 0.1915,  0.1513, -0.0998, -0.1608,  0.1873,  0.2299,  0.2120,  0.0817,
         -0.2764,  0.2690],
        [ 0.3104, -0.0140,  0.2468,  0.1299, -0.0850, -0.1797, -0.2306, -0.2183,
          0.0142,  0.1460],
        [ 0.2945,  0.3125,  0.0708, -0.2314, -0.1121,  0.1275, -0.2641,  0.0205,
          0.1568, -0.0362],
        [ 0.1981, -0.0377,  0.1248, -0.0933,  0.0104,  0.3024, -0.1950,  0.0331,
         -0.2391,  0.0246],
        [ 0.0741,  0.0873,  0.0410, -0.0991,  0.0643, -0.1799, -0.1224,  0.2893,
         -0.1345, -0.3001],
        [-0.2746, -0.1741,  0.1097,  0.2882,  0.1753,  0.0034,  0.0388,  0.1838,
         -0.0462,  0.1986],
        [ 0.3159,  0.3153, -0.1550, -0.1687, -0.2545, -0

Multihead - Encoder


In [63]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math


class MultiHeadEncoder(nn.Module):

    def __init__(self, dim, no_of_heads,dropout):
        super().__init__()

        # ✅ CORRECT: Embedding dimension must be divisible by number of heads
        assert dim % no_of_heads == 0

        self.dim = dim
        self.no_of_heads = no_of_heads
        self.head_vector_dim = dim // no_of_heads

        print("head_vector_dim:", self.head_vector_dim)

        # Query, Key, Value projections
        self.Wq = nn.Linear(dim, dim)
        self.Wk = nn.Linear(dim, dim)
        self.Wv = nn.Linear(dim, dim)

        # Output projection
        self.Wo = nn.Linear(dim, dim)

        # Layer Normalization 1
        self.norm1 = nn.LayerNorm(dim)

        # Feed Forward Network
        self.ffn = nn.Sequential(
            nn.Linear(dim, dim * 4),
            #nn.ReLU(),
            nn.GELU(),
            nn.Linear(dim * 4, dim)
        )

        # Layer Normalization 2
        self.norm2 = nn.LayerNorm(dim)

        #dropout
        self.dropout = nn.Dropout(dropout)

    def selfAttentionMultiHead(self, x):

        batch_size, seq_len, _ = x.shape

        print('x shape in self-attention function', x.shape)

        K = self.Wk(x)
        Q = self.Wq(x)
        V = self.Wv(x)

        print("K shape before :", K.shape)
        print("Q shape before :", Q.shape)
        print("V shape before :", V.shape)

        # ✅ CORRECT: Split embedding dimension into heads
        K = K.view(
            batch_size,
            seq_len,
            self.no_of_heads,
            self.head_vector_dim
        )

        Q = Q.view(
            batch_size,
            seq_len,
            self.no_of_heads,
            self.head_vector_dim
        )

        V = V.view(
            batch_size,
            seq_len,
            self.no_of_heads,
            self.head_vector_dim
        )

        # ✅ CORRECT: Move head dimension to front
        K = K.transpose(1, 2) #e([10, 10]) --> [2,10,5]
        Q = Q.transpose(1, 2)
        V = V.transpose(1, 2)

        print("K shape After :", K.shape)
        print("Q shape After :", Q.shape)
        print("V shape After :", V.shape)

        # ✅ CORRECT: Attention score calculation
        scores = Q @ K.transpose(-2, -1)

        return scores, K, V

    def forward(self, combined_embeddings, attention_mask):

        # Reshape attention_mask for broadcasting with scaled_scores
        # scaled_scores shape: [batch_size, num_heads, seq_len, seq_len]
        # attention_mask needs to be: [batch_size, 1, 1, seq_len]
        if attention_mask.dim() == 2: # Original shape: [batch_size, seq_len]
             attention_mask_reshaped = attention_mask.unsqueeze(1).unsqueeze(2) # Target shape: [batch_size, 1, 1, seq_len]
        else:
             attention_mask_reshaped = attention_mask # Use as is if already reshaped or has different dimensions

        # Multi-head attention
        scores, K, V = self.selfAttentionMultiHead(
            combined_embeddings
        )

        # ✅ CORRECT: Scale by sqrt(head_dim)
        scaled_scores = scores / math.sqrt(
            self.head_vector_dim
        )

        # Apply mask
        scaled_scores = scaled_scores.masked_fill(
            attention_mask_reshaped == 0,
            -1e9
        )

        print("scaled score:",
              scaled_scores)

        # Softmax
        attention_weights = F.softmax(
            scaled_scores,
            dim=-1 #-1 for each row apply softmax to all columns
        )
        print("attention_weights shape:",
              attention_weights.shape)


        #Applying droupout on attention-weights
        dropout_output_1 = self.dropout(
            attention_weights
            )

        print("droupout shape:",
              dropout_output_1.shape)


        # ✅ CORRECT: Context Vector
        context_vector = dropout_output_1 @ V

        print("context_vector shape before concat:",
              context_vector.shape)

        # ✅ CORRECT: Concatenate heads
        batch_size = combined_embeddings.shape[0]
        context_vector = context_vector.transpose(
            1,
            2
        )

        context_vector = context_vector.contiguous().view(
            batch_size,
            combined_embeddings.shape[1],
            self.dim
        )

        print("context_vector shape after concat:",
              context_vector.shape)

        # Output projection
        Wo = self.Wo(context_vector)

        print("Output Projection (Wo) shape :",
              Wo.shape)

        # ✅ CORRECT: Residual Connection 1
        residual_vector_1 = Wo + combined_embeddings

        # ✅ CORRECT: LayerNorm 1
        normalized_vector_1 = self.norm1(
            residual_vector_1
        )

        # Feed Forward Network
        ffn_output = self.ffn(
            normalized_vector_1
        )

        #dropout after FFN
        dropout_output_2 = self.dropout(
            ffn_output
        )

        print("droupout2 shape:",
              dropout_output_2.shape)

        # ✅ CORRECT: Residual Connection 2
        residual_vector_2 = (
            normalized_vector_1 +
            dropout_output_2
        )

        # ✅ CORRECT: LayerNorm 2
        normalized_vector_2 = self.norm2(
            residual_vector_2
        )


        return normalized_vector_2, K, V


In [45]:

# --------------------------
# Example Usage
# --------------------------

# seq_len = 10
# embedding_dim = 10
# num_heads = 2
# batch_size = 1

# encoder = MultiHeadEncoder(
#     embedding_dim,
#     num_heads,
#     dropout=0.1
# )


# # Attention mask
# attention_mask = torch.tensor(
#     attentionMaskList
# )

# print("Attention mask" ,attention_mask)

# print("combined_embedings before : ",combined_embedings)
# combined_embedings = combined_embedings.unsqueeze(0);
# print("combined_embedings After : ",combined_embedings)

# output, K, V = encoder(
#     combined_embedings,
#     attention_mask
# )

# print("\nFinal Output Shape:", output.shape)

In [46]:
class TransformerEncoderStack(nn.Module):

  def __init__(self,embedding_dim,num_heads,dropout,layers):
    super().__init__()

    self.encoderLayers = nn.ModuleList([
               MultiHeadEncoder(
                    embedding_dim,
                    num_heads,
                    dropout
                )
           for _ in range(layers)
    ])

  def forward(self,combined_embedings,attention_mask):
    running_var = combined_embedings

    for encoder in self.encoderLayers:
      output, K, V = encoder(
      running_var,
      attention_mask
      )
      running_var = output

    return running_var, K, V


In [47]:
seq_len = 10
embedding_dim = 10
num_heads = 2
batch_size = 1

print(attention_mask.shape)

te = TransformerEncoderStack(embedding_dim=10,num_heads=2, dropout=0.1, layers=5)

combined_embedings=combined_embedings.unsqueeze(0)

model = te(combined_embedings=combined_embedings,attention_mask=attention_mask)

torch.Size([10])
head_vector_dim: 5
head_vector_dim: 5
head_vector_dim: 5
head_vector_dim: 5
head_vector_dim: 5
x shape in self-attention function torch.Size([1, 10, 10])
K shape before : torch.Size([1, 10, 10])
Q shape before : torch.Size([1, 10, 10])
V shape before : torch.Size([1, 10, 10])
K shape After : torch.Size([1, 2, 10, 5])
Q shape After : torch.Size([1, 2, 10, 5])
V shape After : torch.Size([1, 2, 10, 5])
scaled score: tensor([[[[ 2.8605e-01, -2.7120e-02, -3.3962e-01,  5.7273e-01,  2.3023e-01,
           -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
          [-7.9121e-02,  1.4758e-01,  9.9873e-02, -9.2376e-03,  4.7304e-01,
           -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
          [-1.4181e-02,  1.8126e-01,  2.9046e-02, -3.6873e-01, -7.5832e-01,
           -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
          [-1.7181e-01, -2.9686e-01, -5.3050e-01,  5.1331e-01,  2.1004e-01,
           -1.0000e+09, -1.0000

In [48]:

# --------------------------
# Example Usage
# --------------------------

# seq_len = 10
# embedding_dim = 10
# num_heads = 2
# batch_size = 1

# encoder = MultiHeadEncoder(
#     embedding_dim,
#     num_heads,
#     dropout=0.1
# )


# # Attention mask
# attention_mask = torch.tensor(
#     attentionMaskList
# )

# print("Attention mask" ,attention_mask)

# print("combined_embedings before : ",combined_embedings)
# combined_embedings = combined_embedings.unsqueeze(0);
# print("combined_embedings After : ",combined_embedings)

# output, K, V = encoder(
#     combined_embedings,
#     attention_mask
# )

# print("\nFinal Output Shape:", output.shape)

Training


In [49]:
from os import X_OK
#Read CSV

import pandas as pd

df = pd.read_csv(f"/content/sample_data/sentiment_dataset_sample.csv")

df.head()

X = df['text']
y = df['label']

X,y


(0     A completely average film. Nothing special, bu...
 1     This movie was absolutely fantastic! I loved e...
 2     I fell asleep halfway through. So boring. (Sam...
 3            What a waste of time and money. (Sample 3)
 4     The cinematography was beautiful, and the soun...
                             ...                        
 95    I highly recommend this to anyone who loves sc...
 96    The cinematography was beautiful, and the soun...
 97    I fell asleep halfway through. So boring. (Sam...
 98    This movie was absolutely fantastic! I loved e...
 99    The cinematography was beautiful, and the soun...
 Name: text, Length: 100, dtype: object,
 0     1
 1     1
 2     0
 3     0
 4     1
      ..
 95    1
 96    1
 97    0
 98    1
 99    1
 Name: label, Length: 100, dtype: int64)

In [50]:
df.shape

(100, 2)

In [51]:
X,y

(0     A completely average film. Nothing special, bu...
 1     This movie was absolutely fantastic! I loved e...
 2     I fell asleep halfway through. So boring. (Sam...
 3            What a waste of time and money. (Sample 3)
 4     The cinematography was beautiful, and the soun...
                             ...                        
 95    I highly recommend this to anyone who loves sc...
 96    The cinematography was beautiful, and the soun...
 97    I fell asleep halfway through. So boring. (Sam...
 98    This movie was absolutely fantastic! I loved e...
 99    The cinematography was beautiful, and the soun...
 Name: text, Length: 100, dtype: object,
 0     1
 1     1
 2     0
 3     0
 4     1
      ..
 95    1
 96    1
 97    0
 98    1
 99    1
 Name: label, Length: 100, dtype: int64)

In [52]:

import re

all_vocabulary = set()

for sentence in X:
    # 1. Convert to string and make it lowercase
    text = str(sentence).lower()

    # 2. CLEANING MAGIC: Remove anything that is NOT a letter (a-z) or a space (\s)
    # This automatically deletes numbers like '96' and punctuation like ')'
    clean_text = re.sub(r'[^a-z\s]', '', text)

    # 3. Split the cleaned text into words
    words = clean_text.split()

    # 4. Add the pure words to our set
    all_vocabulary.update(words)

print("Unique pure words (vocab):", len(all_vocabulary))

# Let's peek at a few of the words to prove the numbers are gone!
print(list(all_vocabulary)[:20])

# 1. Create a list of your special tokens
special_tokens = ["<PAD>", "<UNK>", "<CLS>", "<SEP>"]

# 2. Map the special tokens to IDs 0, 1, 2, 3
word_to_id = {token: idx for idx, token in enumerate(special_tokens)}

# 3. Add your clean words to the dictionary, starting at ID 4
for idx, word in enumerate(all_vocabulary):
    word_to_id[word] = idx + len(special_tokens)

print(f"Success! Your dictionary has {len(word_to_id)} total tokens.")
print("Special Token IDs:", {k: word_to_id[k] for k in special_tokens})

Unique pure words (vocab): 75
['nothing', 'a', 'either', 'through', 'recommend', 'director', 'the', 'cinematography', 'loved', 'this', 'beautiful', 'plot', 'surprised', 'time', 'film', 'money', 'highly', 'but', 'average', 'it']
Success! Your dictionary has 79 total tokens.
Special Token IDs: {'<PAD>': 0, '<UNK>': 1, '<CLS>': 2, '<SEP>': 3}


In [53]:
vocab_dict = word_to_id

In [54]:
vocab_dict

{'<PAD>': 0,
 '<UNK>': 1,
 '<CLS>': 2,
 '<SEP>': 3,
 'nothing': 4,
 'a': 5,
 'either': 6,
 'through': 7,
 'recommend': 8,
 'director': 9,
 'the': 10,
 'cinematography': 11,
 'loved': 12,
 'this': 13,
 'beautiful': 14,
 'plot': 15,
 'surprised': 16,
 'time': 17,
 'film': 18,
 'money': 19,
 'highly': 20,
 'but': 21,
 'average': 22,
 'it': 23,
 'than': 24,
 'ive': 25,
 'so': 26,
 'terrible': 27,
 'year': 28,
 'all': 29,
 'absolutely': 30,
 'an': 31,
 'minute': 32,
 'masterpiece': 33,
 'reviews': 34,
 'anyone': 35,
 'completely': 36,
 'loves': 37,
 'scifi': 38,
 'acting': 39,
 'waste': 40,
 'read': 41,
 'much': 42,
 'i': 43,
 'not': 44,
 'perfectly': 45,
 'asleep': 46,
 'movie': 47,
 'halfway': 48,
 'sample': 49,
 'pleasantly': 50,
 'do': 51,
 'themselves': 52,
 'book': 53,
 'sense': 54,
 'buy': 55,
 'fell': 56,
 'boring': 57,
 'soundtrack': 58,
 'fantastic': 59,
 'suggested': 60,
 'special': 61,
 'outdid': 62,
 'no': 63,
 'absolute': 64,
 'every': 65,
 'to': 66,
 'better': 67,
 'wooden': 

In [55]:
X[:5]

,text
0,"A completely average film. Nothing special, bu..."
1,This movie was absolutely fantastic! I loved e...
2,I fell asleep halfway through. So boring. (Sam...
3,What a waste of time and money. (Sample 3)
4,"The cinematography was beautiful, and the soun..."


In [56]:
X.shape

(100,)

In [57]:
seq_len = 100

In [58]:
import re
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# ==========================================
# 1. DATA PREPROCESSING
# ==========================================
all_token_ids = []

for sentence in X:
    clean_text = re.sub(r'[^a-z\s]', '', str(sentence).lower())
    words = clean_text.split()

    unk_id = vocab_dict["<UNK>"]
    word_ids = [vocab_dict.get(w, unk_id) for w in words]

    token_ids = [vocab_dict["<CLS>"]] + word_ids + [vocab_dict["<SEP>"]]

    if len(token_ids) > seq_len:
        token_ids = token_ids[:seq_len]
        token_ids[-1] = vocab_dict["<SEP>"]
    else:
        pad_id = vocab_dict["<PAD>"]
        token_ids = token_ids + [pad_id] * (seq_len - len(token_ids))

    all_token_ids.append(token_ids)

X_tensor = torch.tensor(all_token_ids, dtype=torch.long)

# Create attention mask
pad_id = vocab_dict["<PAD>"]
attention_mask = (X_tensor != pad_id).long()

# Convert labels to tensor
y_tensor = torch.tensor(y.values, dtype=torch.long)

# Set batch size for DataLoader
batch_size = 10 # Assuming a reasonable batch size, adjust if needed

# Create TensorDataset
dataset = TensorDataset(X_tensor, attention_mask, y_tensor)

# Create DataLoader
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [66]:
import torch.nn as nn

# Define a Transformer-based model for sentiment classification
class SentimentTransformer(nn.Module):

    # Constructor: runs once when model object is created
    def __init__(
        self,
        vocab_size,      # Total number of words/tokens in vocabulary
        embedding_dim,   # Size of embedding vector for each token
        num_heads,       # Number of attention heads in multi-head attention
        dropout,         # Dropout probability
        layers,          # Number of encoder layers
        num_classes      # Number of output classes (e.g. Positive/Negative)
    ):

        # Initialize parent nn.Module class
        super(SentimentTransformer, self).__init__()

        # Embedding layer
        # Converts token IDs into dense vectors
        # Shape:
        # Input  -> (batch_size, seq_len)
        # Output -> (batch_size, seq_len, embedding_dim)
        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim
        )

        # Transformer Encoder Stack
        # Learns contextual relationships between words
        self.encoder = TransformerEncoderStack(
            embedding_dim=embedding_dim,
            num_heads=num_heads,
            dropout=dropout,
            layers=layers
        )

        # Final classification layer
        # Converts sentence representation into class scores
        # Shape:
        # Input  -> (batch_size, embedding_dim)
        # Output -> (batch_size, num_classes)
        self.classifier = nn.Linear(
            embedding_dim,
            num_classes
        )

    # Forward pass
    # Executes when model(input_ids, attention_mask) is called
    def forward(self, input_ids, attention_mask):

        # Convert token IDs into embeddings
        #
        # Example:
        # input_ids = [[4,7,9]]
        #
        # Output:
        # [
        #   [0.1,0.5,...],
        #   [0.7,0.2,...],
        #   [0.3,0.9,...]
        # ]
        embeddings = self.embedding(input_ids)

        # Pass embeddings through Transformer Encoder
        #
        # Encoder returns:
        # enc_out          -> contextualized token vectors
        # attention_scores -> attention weights
        # other output     -> any extra returned value
        enc_out, _, _ = self.encoder(
            combined_embedings=embeddings,
            attention_mask=attention_mask
        )

        # Select first token representation
        #
        # Shape of enc_out:
        # (batch_size, seq_len, embedding_dim)
        #
        # [:,0,:] means:
        # all batches
        # first token only
        # all embedding dimensions
        #
        # Often used as CLS token representation
        print("encoder output",enc_out)
        cls_token_out = enc_out[:, 0, :]

        # Pass CLS vector through classifier
        #
        # Output:
        # logits (unnormalized class scores)
        #
        # Example:
        # [2.3, -1.1]
        logits = self.classifier(cls_token_out)

        # Return class scores
        return logits

In [ ]:
# ==========================================
# 3. INITIALIZATION & TRAINING
# ==========================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = SentimentTransformer(
    vocab_size=len(vocab_dict),
    embedding_dim=100,
    num_heads=2,
    dropout=0.1,
    layers=5,
    num_classes=2
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 5

for epoch in range(epochs):
    model.train()
    total_loss = 0
    correct_predictions = 0
    total_samples = 0

    for batch_X, batch_mask, batch_y in train_loader:

        batch_X = batch_X.to(device)
        batch_mask = batch_mask.to(device)
        batch_y = batch_y.long().to(device)

        # The attention mask reshaping is now handled inside the MultiHeadEncoder.
        # The original batch_mask (shape [batch_size, seq_len]) is passed directly.

        optimizer.zero_grad()

        logits = model(input_ids=batch_X, attention_mask=batch_mask)
        loss = criterion(logits, batch_y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        predictions = torch.argmax(logits, dim=1)
        correct_predictions += (predictions == batch_y).sum().item()
        total_samples += batch_y.size(0)

    avg_loss = total_loss / len(train_loader)
    accuracy = (correct_predictions / total_samples) * 100
    print(f"Epoch {epoch+1}/{epochs} | Loss: {avg_loss:.4f} | Accuracy: {accuracy:.2f}%")

print("Training Complete! 🚀")





Streaming output truncated to the last 5000 lines.
           -1.0000e+09, -1.0000e+09],
          [ 5.1790e-01, -1.6912e-01, -1.5497e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [ 1.6671e-01,  2.0859e-01,  1.2750e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          ...,
          [ 1.9851e-01,  4.2769e-01,  5.2525e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [ 1.8001e-01,  3.8008e-01,  5.1168e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [ 2.7152e-01,  4.6135e-01,  5.4572e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09]],

         [[-2.5032e+00, -5.8439e-01,  1.7890e+00,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [-1.6342e-01,  5.4531e-01,  8.8559e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [-4.6876e-01, -8.3341e-02,  8.3888e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          ...,
          [-2.2786e-01,

In [73]:
# ==========================================
# 4. PREDICTION FOR A NEW SENTENCE
# ==========================================

def predict_sentiment(sentence: str, model, vocab_dict, seq_len, device):
    model.eval() # Set model to evaluation mode

    # 1. Preprocessing (similar to training data)
    clean_text = re.sub(r'[^a-z\s]', '', str(sentence).lower())
    words = clean_text.split()

    unk_id = vocab_dict["<UNK>"]
    # Convert words to IDs, add CLS and SEP tokens
    token_ids = [vocab_dict["<CLS>"]] + [vocab_dict.get(w, unk_id) for w in words] + [vocab_dict["<SEP>"]]

    # Apply sequence length truncation or padding
    if len(token_ids) > seq_len:
        token_ids = token_ids[:seq_len]
        token_ids[-1] = vocab_dict["<SEP>"] # Ensure SEP is at the end if truncated
    else:
        pad_id = vocab_dict["<PAD>"]
        token_ids = token_ids + [pad_id] * (seq_len - len(token_ids))

    # Convert to tensor
    input_ids = torch.tensor([token_ids], dtype=torch.long).to(device)

    # Create attention mask
    attention_mask = (input_ids != vocab_dict["<PAD>"]).long().to(device)

    # 2. Make prediction
    with torch.no_grad(): # Disable gradient calculations for inference
        logits = model(input_ids=input_ids, attention_mask=attention_mask)
        probabilities = torch.softmax(logits, dim=1)
        predicted_class = torch.argmax(probabilities, dim=1).item()

    # 3. Interpret result
    sentiment_label = "Positive" if predicted_class == 1 else "Negative"
    return sentiment_label, probabilities[0][predicted_class].item()

# Example Usage:
new_sentence_1 = "This movie was absolutely fantastic, I loved every minute of it!"
new_sentence_2 = "good day."

# Assuming `vocab_dict` and `seq_len` are defined from previous cells
predicted_sentiment_1, confidence_1 = predict_sentiment(new_sentence_1, model, vocab_dict, seq_len, device)
print(f"Sentence: '{new_sentence_1}'\nPredicted Sentiment: {predicted_sentiment_1} (Confidence: {confidence_1:.2f})\n")

predicted_sentiment_2, confidence_2 = predict_sentiment(new_sentence_2, model, vocab_dict, seq_len, device)
print(f"Sentence: '{new_sentence_2}'\nPredicted Sentiment: {predicted_sentiment_2} (Confidence: {confidence_2:.2f})\n")

x shape in self-attention function torch.Size([1, 100, 100])
K shape before : torch.Size([1, 100, 100])
Q shape before : torch.Size([1, 100, 100])
V shape before : torch.Size([1, 100, 100])
K shape After : torch.Size([1, 2, 100, 50])
Q shape After : torch.Size([1, 2, 100, 50])
V shape After : torch.Size([1, 2, 100, 50])
scaled score: tensor([[[[-1.3025e+00,  6.3336e-01, -6.1440e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [-4.8626e-01,  1.4137e-01, -7.9598e-02,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [-3.7810e-01,  3.2107e-01,  4.4902e-01,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          ...,
          [ 1.9563e-01, -4.3571e-01,  2.3960e-02,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [ 1.9563e-01, -4.3571e-01,  2.3960e-02,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09],
          [ 1.9563e-01, -4.3571e-01,  2.3960e-02,  ..., -1.0000e+09,
           -1.0000e+09, -1.0000e+09]],

     