<a href="https://colab.research.google.com/github/heyanugrah/Transformers/blob/main/codeTransformerMe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import random

In [2]:
from torch import nn

In [3]:
word = "anugrah is learning"

In [4]:
vocab = ["<pad>","anugrah","is","learning","[SEP]","<unk>","<CLS>"];

In [5]:

vocab_dict={}

#creating vocabulory
for index,vocab_item in enumerate(vocab):
  vocab_dict[index] = vocab_item

In [6]:
""
print(vocab_dict)

{0: '<pad>', 1: 'anugrah', 2: 'is', 3: 'learning', 4: '[SEP]', 5: '<unk>', 6: '<CLS>'}


In [7]:
input_text = "anugrah is learning okay.oo"

In [8]:
#Tokenize and Add CLS,PAD and SEP token with input

tokenList = []

tokenList.append("[CLS]")

for word in input_text.split():

    # Check for sentence ending with '.'
    if word.endswith("."):

        clean_word = word[:-1]

        if clean_word in vocab:
            tokenList.append(clean_word)
        else:
            tokenList.append("<unk>")

        tokenList.append("[SEP]")

    else:

        if word in vocab:
            tokenList.append(word)
        else:
            tokenList.append("<unk>")

# Add final separator if not already present
if tokenList[-1] != "[SEP]":
    tokenList.append("[SEP]")

print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [9]:
print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [10]:
#convert the tokenList to tokenId

In [11]:
tokenIDList = []
print(tokenList)

['[CLS]', 'anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [12]:
vectorList = []

#converting wordList to vectorList
for word in tokenList:
    for key, value in vocab_dict.items():
        if value == word:
            #print(word, "->", key)
            vectorList.append(key)
            tokenIDList.append(value)

In [13]:
print(vectorList)
print(tokenIDList)

[1, 2, 3, 5, 4]
['anugrah', 'is', 'learning', '<unk>', '[SEP]']


In [14]:
max_seq_length = 10 #total of 10 words in a sentence

# Adding padding zero to make sequence length equal
while len(vectorList) < max_seq_length:
    vectorList.append(0)

vectorList


[1, 2, 3, 5, 4, 0, 0, 0, 0, 0]

In [15]:
#creating attention mask
attentionMaskList = []

attentionMaskList = [1 if token != 0 else 0 for token in vectorList]
print(attentionMaskList)

[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]


In [16]:
#token embbedings

In [17]:
import torch.nn as nn

In [18]:
#convert list to tensors

In [19]:
trs = torch.tensor(vectorList)
type(trs)

torch.Tensor

In [20]:
dim = 10
embbedings = nn.Embedding(
    num_embeddings=dim,
    embedding_dim=dim
)

In [21]:
embedings = embbedings(trs)

In [22]:
embedings

tensor([[ 1.6298,  1.7398, -1.3912, -1.5001, -0.0685, -0.3587,  0.5005, -1.6975,
         -1.1706, -0.8228],
        [ 0.9511,  0.6724, -0.1955,  0.0756,  0.1532,  1.0622, -0.5593,  0.1499,
          1.9765, -1.4996],
        [ 0.2039, -1.5893, -0.8544, -0.3906,  0.4229,  0.5645, -0.4756, -0.5177,
          0.3220,  0.1581],
        [ 0.6647,  0.0685,  0.6327, -1.3493,  0.0960,  0.3808,  1.0003, -0.9343,
         -0.9511, -0.5634],
        [-1.4789, -2.0218,  1.2083,  0.8921,  0.8780, -0.3746,  0.3209, -1.5950,
         -1.4926,  0.6483],
        [ 0.8601,  0.2913,  0.0317,  0.4386, -1.4700,  0.0736, -0.9359,  0.2113,
         -0.1399, -0.0857],
        [ 0.8601,  0.2913,  0.0317,  0.4386, -1.4700,  0.0736, -0.9359,  0.2113,
         -0.1399, -0.0857],
        [ 0.8601,  0.2913,  0.0317,  0.4386, -1.4700,  0.0736, -0.9359,  0.2113,
         -0.1399, -0.0857],
        [ 0.8601,  0.2913,  0.0317,  0.4386, -1.4700,  0.0736, -0.9359,  0.2113,
         -0.1399, -0.0857],
        [ 0.8601,  

In [23]:
embedings.shape #10 tokens , #10 dimensional

torch.Size([10, 10])

In [24]:
#positional encoding

In [25]:

'''
Formula:

PE(pos, 2i)   = sin(pos / 10000^(2i/d_model))
    PE(pos, 2i+1) = cos(pos / 10000^(2i/d_model))
'''
import math

pev = torch.zeros(max_seq_length, dim) #position encoding vector
pev

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
pev.shape

torch.Size([10, 10])

In [27]:
#position
position = torch.arange(0,10)
position

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
position.shape

torch.Size([10])

In [29]:
#add the shape to make matrix addition
position = position.unsqueeze(1)

In [30]:
position

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [31]:
position.shape

torch.Size([10, 1])

In [32]:
print(pev)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [33]:
div_term = torch.exp(
    torch.arange(0, dim, 2)
    * (-math.log(10000.0) / dim)
)

#controlling oscillation speed of sin and cos waves
print(div_term)

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])


In [34]:
pev[:, 0::2] = torch.sin(position * div_term) #even apply, start from 0 to end , every second number
pev[:, 1::2] = torch.cos(position * div_term) #odd apply, start from 0 to end , every second number

In [35]:
print(pev)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
          9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
          9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
          9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
          9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00],
        [-9.5892e-01,  2.8366e-01,  7.1207e-01,  7.0211e-01,  1.2526e-01,
          9.9212e-01,  1.9904e-02,  9.9980e-01,  3.1548e-03,  1.0000e+00],
        [-2.7942e-01,  9.6017e-01,  8.1396e-01,  5.8092e-01,  1.5014e-01,
          9.8866e-01,  2.3884e-0

In [36]:
combined_embedings = pev + embedings #CE = PE + Embbedings

In [37]:
print(combined_embedings)

tensor([[ 1.6298,  2.7398, -1.3912, -0.5001, -0.0685,  0.6413,  0.5005, -0.6975,
         -1.1706,  0.1772],
        [ 1.7925,  1.2127, -0.0377,  1.0631,  0.1784,  2.0619, -0.5553,  1.1499,
          1.9771, -0.4996],
        [ 1.1132, -2.0055, -0.5427,  0.5595,  0.4731,  1.5633, -0.4676,  0.4823,
          0.3233,  1.1581],
        [ 0.8058, -0.9215,  1.0904, -0.4603,  0.1713,  1.3780,  1.0122,  0.0656,
         -0.9492,  0.4366],
        [-2.2357, -2.6755,  1.8007,  1.6978,  0.9783,  0.6203,  0.3369, -0.5951,
         -1.4901,  1.6483],
        [-0.0988,  0.5750,  0.7438,  1.1407, -1.3447,  1.0658, -0.9159,  1.2111,
         -0.1368,  0.9143],
        [ 0.5807,  1.2515,  0.8457,  1.0195, -1.3198,  1.0623, -0.9120,  1.2110,
         -0.1361,  0.9143],
        [ 1.5171,  1.0452,  0.9272,  0.8838, -1.2950,  1.0582, -0.9080,  1.2109,
         -0.1355,  0.9143],
        [ 1.8495,  0.1458,  0.9862,  0.7369, -1.2704,  1.0535, -0.9040,  1.2108,
         -0.1349,  0.9142],
        [ 1.2723, -

In [38]:
print(combined_embedings.shape)

torch.Size([10, 10])


In [39]:
dim

10

In [40]:
#Encoder
import torch.nn.functional as F

class Encoder(nn.Module):

  def __init__(self):
      super().__init__()
      self.dim = dim
      self.Wq = nn.Linear(dim,dim) #weightedQuery
      self.Wk = nn.Linear(dim,dim) #weightKey
      self.Wv = nn.Linear(dim,dim) #weightedValue

      #normalization 1
      self.norm1 = nn.LayerNorm(dim)

      #feed forward nueral network
      self.ffn = nn.Sequential(
           nn.Linear(dim,dim * 4),
           nn.ReLU(),
           nn.Linear(dim * 4,dim)
      )

      #normalization 2
      self.norm2 = nn.LayerNorm(dim)

  def selfAttention(self, x):
        # K and Q are already the results of the linear projection
        K = self.Wk(x)
        Q = self.Wq(x)
        V = self.Wv(x)

        # Use @ for matrix multiplication and .transpose() for the Key
        scores = Q @ K.transpose(-2, -1)

        print('key shape : ',K.shape)
        return scores,K,V

  def forward(self,combined_embedings):

    #calculating self attention
    scores,K,V = self.selfAttention(combined_embedings)

    #scaled self attention
    scaled_score = scores / math.sqrt(self.dim) #dimension of key

    #applying softmax to context_vector
    context_vector = F.softmax(scaled_score, dim=-1) @ V

    #adding residual connection 1 (context_vector + combined_embedings)
    residual_vector_1 = context_vector + combined_embedings

    #normalization of residual vector
    normalized_vector_1 = self.norm1(residual_vector_1)

    print('context scores: ',scores.shape)
    print('scores: ',scores.shape)
    print('scaled scores: ',scores.shape)

    #Feeding to Feed Forward nw
    ffn_output = self.ffn(normalized_vector_1)

    #residual connection 2 (normalized_vector + ffn_output)
    residual_vector_2 = normalized_vector_1 + ffn_output

    #normalization 2
    normalized_vector_2 = self.norm2(residual_vector_2)

    return normalized_vector_2,K,V


$$\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V$$

In [41]:
encoderLayer = Encoder()
encoder_output,K,V = encoderLayer(combined_embedings)

print("encoder_output :" ,encoder_output)
print("key vector to decoder ", K)
print("Value vector to decoder ", V)


key shape :  torch.Size([10, 10])
context scores:  torch.Size([10, 10])
scores:  torch.Size([10, 10])
scaled scores:  torch.Size([10, 10])
encoder_output : tensor([[ 0.7106,  2.0318, -1.4082, -0.2636, -0.2714,  0.1468,  0.9147, -0.1597,
         -1.5251, -0.1758],
        [ 0.5850,  0.2810, -1.3566,  0.3134, -0.7390,  1.2171, -0.6650,  1.3550,
          0.6970, -1.6878],
        [-0.1457, -2.1599, -1.0625,  0.2105,  0.1871,  1.0229, -0.1519,  1.4955,
         -0.2533,  0.8573],
        [-0.1653, -1.6925,  0.3033, -0.6693, -0.0048,  1.2242,  1.3457,  1.0529,
         -1.4646,  0.0706],
        [-1.9131, -1.6720,  0.3861,  0.7614,  0.6361,  0.4697,  0.7552,  0.5675,
         -0.8011,  0.8101],
        [-1.1995, -0.1731, -0.2889,  0.6926, -1.3991,  1.0128, -0.4367,  2.0873,
         -0.5913,  0.2960],
        [-0.6979,  0.3500, -0.2412,  0.5583, -1.6530,  0.8911, -0.6838,  2.0873,
         -0.7968,  0.1860],
        [ 0.1952,  0.0384, -0.1032,  0.3959, -1.7622,  0.7676, -0.9389,  2.0967,


In [42]:
# Accessing the weight matrix
print("Wq weight shape:", encoderLayer.Wq.weight.shape)
print("Wq weight:\n", encoderLayer.Wq.weight)

# Accessing the bias vector
print("Wq bias shape:", encoderLayer.Wq.bias.shape)
print("Wq bias:\n", encoderLayer.Wq.bias)

Wq weight shape: torch.Size([10, 10])
Wq weight:
 Parameter containing:
tensor([[ 0.1573,  0.1885,  0.3044, -0.0048,  0.3147, -0.0580,  0.2490, -0.2846,
         -0.0076, -0.2409],
        [-0.0265,  0.1170,  0.1621,  0.3089,  0.0044, -0.0432, -0.1781,  0.2045,
          0.1622,  0.2725],
        [-0.2443,  0.1318,  0.1167, -0.2083, -0.0981,  0.0939, -0.0290, -0.1499,
         -0.0873,  0.1083],
        [-0.1258, -0.1232, -0.2846, -0.1213,  0.1667, -0.3012,  0.2932,  0.0293,
          0.2302,  0.2520],
        [-0.1643, -0.1816, -0.0380, -0.0654,  0.0051, -0.0775, -0.0605,  0.0406,
          0.0352,  0.3158],
        [ 0.2558,  0.3028,  0.0387,  0.1346, -0.2123,  0.1246,  0.1747,  0.0222,
          0.1918, -0.1941],
        [-0.1594,  0.0041,  0.1026, -0.0653, -0.0292,  0.0005, -0.0890,  0.0057,
         -0.2908, -0.0882],
        [ 0.0367, -0.2066, -0.0725,  0.2519,  0.1101, -0.1937,  0.2276,  0.2731,
         -0.2039,  0.1005],
        [-0.0636, -0.1064,  0.2073,  0.0899, -0.1983, -0